version: "3.7"

services:
  postgresql:
    image: postgres:10.1-alpine
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    restart: on-failure

  library:
    container_name: library
    build:
      context: ./
    command:  bash -c "python ./library/manage.py migrate --noinput &&
              python ./library/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - postgresql
      - redis

volumes:
  postgres_data: